config/routes.rb
Motoprieks::Application.routes.draw do
  get "login" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  resources :users
  resources :sessions
  resources :categories
  resources :images

  match 'code_image/:id' => 'images#code_image'
  get "destroy" => "posts#destroy", :as => "destroy"
  get "admin_category" => "posts#admin_category", :as => "admin_category"
  get "create_category" => "posts#create_category", :as => "create_category"
  get "edit_category" => "posts#edit_category", :as => "edit_category"
  resources :posts do
    resources :comments
  end
  resources :mains
  get "show_category" => "mains#show_category", :as => "show_category"
  root :to => "mains#index"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  
  attr_accessible :login, :password, :password_confirmation, :mail, :website, :status

  attr_accessor :password

  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :login
  validates_uniqueness_of :login
  validates_presence_of :password, :on => :create
  validates_presence_of :mail
  validates_uniqueness_of :mail
  validates_format_of :mail, :with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i
  
  
  def self.authenticate(login, password)
    user = find_by_login(login)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
    nil
    end
  end  
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :admin_required, :except => ["new", "create", "index", "show"]
  def index
    @users = User.all
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    @user.status = 0
    @user.status = 2 if  @user.login == "eriks"

    if @user.save
      redirect_to root_url, :notice =>"Signed Up!"
    else
      render "new"
    end  
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(:back, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h2>Editing user</h2>
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :login %><br />
    <%= f.text_field :login %>
  </div>
  <div class="field">
    <%= f.label :mail %><br />
    <%= f.text_field :mail %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.select :status, { "Commenter" => "0", "Editor" => "1", "Admin" => "2"} %>
  </div><br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= link_to 'Back', :back %> | <%= link_to 'Admin Panel', posts_path %>

app/views/users/index.html.erb
<table>
<tr>
    <th>Login</th>
    <th>Created at</th>
    <th><%= label_tag :edit if admin_user %></th>
    <th><%= label_tag :destroy if admin_user%></th>
</tr>
<% @users.each do |u| %>
<ul id="category_list">
  <tr>
    <td><%= link_to u.login, u.website %></td>
    <td><%= u.created_at.strftime("%B %d %Y") %></td>
    <td><%= link_to 'Edit', edit_user_path(u) if admin_user %></td>
    <td><%= link_to 'Destroy', u, :confirm => 'Are you sure?', :method => :delete if admin_user %></td>
  </tr>
  </ul>
<% end %>
</table>
<br />
<%= link_to 'New User', new_user_path %> | <%= link_to 'Admin Panel', posts_path %>

app/views/users/new.html.erb
<div id="mainleft">
<h2>Sign Up</h2>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
  <%= f.label :login %><br>
  <%= f.text_field :login %>
  </div>
  <div class="field">
  <%= f.label :mail %><br>
  <%= f.text_field :mail %>
  </div>
  <div class="field">
  <%= f.label :password %><br>
  <%= f.password_field :password %>
  </div>
  <div class="field"> 
  <%= f.label :password_confirmation %><br>
  <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
  <%= f.label :website %><br>
  <%= f.text_field :website, :value => 'http://www.'  %>
  </div>
  <div class="action"><%= f.submit %></div>
<% end %>
<%= link_to "Back", :back %> | <%= link_to 'Admin Panel', posts_path if editor_user || admin_user %>
</div>

<%= render 'mains/category' %> 