config/routes.rb
Motoprieks::Application.routes.draw do
  get "login" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  resources :users
  resources :sessions
  resources :categories
  resources :images

  match 'code_image/:id' => 'images#code_image'
  get "destroy" => "posts#destroy", :as => "destroy"
  get "admin_category" => "posts#admin_category", :as => "admin_category"
  get "create_category" => "posts#create_category", :as => "create_category"
  get "edit_category" => "posts#edit_category", :as => "edit_category"
  resources :posts do
    resources :comments
  end
  resources :mains
  get "show_category" => "mains#show_category", :as => "show_category"
  root :to => "mains#index"
end

app/models/post.rb
class Post < ActiveRecord::Base
  cattr_reader :per_page
  @@per_page = 8

  validates_presence_of :title, :body
  validates_uniqueness_of :title
  has_many :comments
  belongs_to :user
  belongs_to :category
  belongs_to :image
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
 before_filter :login_required
 
uses_tiny_mce(:options => {:theme => 'advanced',
  :browsers => %w{msie gecko},
  :theme_advanced_toolbar_location => "top",
  :theme_advanced_toolbar_align => "left",
  :theme_advanced_resizing => true,
  :theme_advanced_resize_horizontal => false,
  :paste_auto_cleanup_on_paste => true,
  :theme_advanced_buttons1 => %w{formatselect fontselect fontsizeselect bold italic underline strikethrough separator justifyleft justifycenter justifyright separator indent outdent separator bullist numlist forecolor backcolor},
  :theme_advanced_buttons2 => %w{ link unlink undo redo emotions },
  :theme_advanced_buttons3 => [],
  :plugins => %w{contextmenu paste emotions}},
  :only => [:new, :create, :edit, :update, :show]) 
  
  $categories = Category.all
  $users = User.all
  $images = Image.all

  def index
    @posts = Post.find(:all,:order => "created_at DESC")
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @posts }
    end
  end

  def show
  @post = Post.find(params[:id]) rescue nil
  if @post.nil?
  redirect_to root_url
  else
   respond_to do |format|
      format.html 
      format.xml  { render :xml => @post }
    end
  end
  end

  def new
    @post = Post.new
    respond_to do |format|
      format.html 
      format.xml  { render :xml => @post }
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(params[:post])
    @post.user_id = session[:user_id] if !admin_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to(@post, :notice => 'Post was successfully created.') }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @post = Post.find(params[:id])
    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to(@post, :notice => 'Post was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to(posts_url) }
      format.xml  { head :ok }
    end
  end
  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :category %><br />
    <%= collection_select(:post, :category_id, $categories ,:id, :name) %></p>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body, :class => "mceEditor" %>
  </div>
  <div class="field">
    <%= f.label :main_image %><br />
    <%= collection_select(:post, :image_id, $images, :id, :filename)%>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.check_box :status %>
  </div>
  <div class="field">
    <%= f.label :user_id  if admin_user %><br />
    <%= collection_select(:post, :user_id, $users, :id, :login) if admin_user %>
  </div>
  <div class="field">
    <%= f.label :current_user %><br />
    <% if current_user %>
          <%= current_user.login %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %> | <%= link_to 'Show', @post %> | <%= link_to 'Admin Panel', posts_path %>

app/views/posts/index.html.erb
<table border="1" width="800">
    <tr>
      <th>Listing posts</th>
      <th>Category list</th>
      <th>Users list</th>
      <th>Images</th>
    </tr>
<tr>
    <td rowspan="2" width="400" >
          <table>
          
            <tr>
              <th>Title</th>
              <th>Author</th>
              <th>Created at</th>
              <th><%= label_tag :edit if editor_user || admin_user %></th>
              <th><%= label_tag :destroy if admin_user %></th>
            </tr>

          <% @posts.each do |post| %>
            <tr>
              <td><%= link_to post.title, post %></td>
              <td><%= post.user.login %></td>
              <td><%= post.created_at.strftime("%B %d %Y") %></td>
              <td><%= link_to 'Edit', edit_post_path(post) if editor_user || admin_user %></td>
              <td><%= link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete if admin_user %></td>
            </tr>
          <% end %>
          
          </table>
          <%= link_to 'New Post', new_post_path if editor_user || admin_user %>
     </td>
    <td width="200">
          <ul id="category_list">
              <% Category.all.each do |c| %>
                <li><%= link_to c.name, categories_path %></li>
              <% end %>
          </ul>
          <%= link_to 'New Category', new_category_path if editor_user || admin_user %>
    </td>
    <td width="200">
      <ul id="category_list">
        <% User.all.each do |u| %>
          <li><%= link_to u.login, users_path %></li>
        <% end %>
      </ul>
      <%= link_to 'New User', new_user_path if editor_user || admin_user %>
    </td>
    <td width="200">
      <ul id="category_list">
        <% Image.all.each do |i| %>
          <li><%= link_to i.filename, images_path %></li>
        <% end %>
      </ul>
      <%= link_to 'New Image', new_image_path if editor_user || admin_user %> 
    </td>
</tr>
</table>
<br>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %> | <%= link_to 'Admin Panel', posts_path %>

app/views/posts/show.html.erb
<p>
  <b>Category:</b>
  <%= @post.category.name %>
</p>
<p>
  <b>Title:</b>
  <%= @post.title %>
</p>
<p>
  <b>Image:</b>
  <%= raw image_tag("/code_image/#{@post.image_id}", :alt => @post.image.description ) %>
</p>
<p>
  <b>Body:</b>
  <%= raw @post.body %>
</p>
<strong>Category: </strong> <%= link_to @post.category.name, :action => "admin_category", :id => @post.category.id %><br />

<p>
  <b>Author:</b>
  <%= @post.user.login %>
</p>
<%= link_to 'Back', :back %> | <%= link_to 'Admin Panel', posts_path %>

<h2>Comments</h2>
<% @post.comments.each do |comment| %>
  <p>
    <b>Commenter:</b>
    <%= link_to @post.user.login, @post.user.website %>
  </p>
  <p>
    <b>Comment:</b>
    <%= comment.body %>
  </p>
<% end %>

<h2>Add a comment:</h2>
<%= form_for([@post, @post.comments.build]) do |f| %>

  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>