config/routes.rb
Motoprieks::Application.routes.draw do
  get "login" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  resources :users
  resources :sessions
  resources :categories
  resources :images

  match 'code_image/:id' => 'images#code_image'
  get "destroy" => "posts#destroy", :as => "destroy"
  get "admin_category" => "posts#admin_category", :as => "admin_category"
  get "create_category" => "posts#create_category", :as => "create_category"
  get "edit_category" => "posts#edit_category", :as => "edit_category"
  resources :posts do
    resources :comments
  end
  resources :mains
  get "show_category" => "mains#show_category", :as => "show_category"
  root :to => "mains#index"
end

app/models/image.rb
class Image < ActiveRecord::Base
  validates_presence_of :description
  has_many :posts

  def image_file=(input_data)
    self.filename = input_data.original_filename
    self.content_type = input_data.content_type.chomp
    self.binary_data = input_data.read
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_filter :login_required, :except => ["code_image"]
  def index
    @images = Image.all
    respond_to do |format|
      format.html
      format.xml  { render :xml => @images }
    end
  end
  
  def show
    @image = Image.find(params[:id])
    respond_to do |format|
      format.html
      format.xml { render :xml => @image }
    end
  end
   
  def new
    @image = Image.new
    respond_to do |format|
      format.html 
      format.xml  { render :xml => @image }
    end
  end
  
  def edit
     @image = Image.find(params[:id])
  end
  
  def create
    @image = Image.new(params[:image])
    respond_to do |format|
      if @image.save
        format.html { redirect_to(@image, :notice => 'Image was successfully created.') }
        format.xml  { render :xml => @image, :status => :created, :location => @image }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @image.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def update
    @image = Image.find(params[:id])
    respond_to do |format|
      if @image.update_attributes(params[:image])
        format.html { redirect_to(@image, :notice => 'Image was successfully updated.') } 
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @image.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def code_image 
    @image_data = Image.find(params[:id])
    @image = @image_data.binary_data
    send_data @image, :type => @image_data.content_type, :filename => @image_data.filename, :disposition => 'inline'
  end
  
  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    respond_to do |format|
      format.html { redirect_to(images_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<%= form_for @image, :html=>{:multipart=>true} do |i| %>
  <% if @image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>
      <ul>
      <% @image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
   <%= i.file_field :image_file %>
   <%= i.text_field :description %>
  </div>
 
  <br />
  <div class="actions">
    <%= i.submit %>
  </div>
<% end %>

app/views/images/edit.html.erb
<h1>Editing image</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %> | <%= link_to 'Admin Panel', posts_path %>

app/views/images/index.html.erb
<% @images.each do |image| %>

<%= link_to(image) do %>
          <h2><%= image.filename %><div id="date"><%= image.created_at.strftime("%m/%d/%Y") %></div></h2>
      <% end %>
<p><%= raw image_tag("/code_image/#{image.id}", :alt => "Image", :size => "160x160") %></p>
<p><%= image.description %></p>
<p><%= link_to 'Edit',edit_image_path(image) if editor_user || admin_user %> |
<%= link_to 'Destroy', image, :confirm => 'Are you sure?', :method => :delete if admin_user %></p>
<% end %>

<br />
<%= link_to "Back", :back %> | <%= link_to 'New Image', new_image_path %> | <%= link_to 'Admin Panel', posts_path %>

app/views/images/new.html.erb
<h1>New Image</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %> | <%= link_to 'Admin Panel', posts_path %>

app/views/images/show.html.erb
<h2><%= @image.filename %><div id="date"><%= @image.created_at.strftime("%m/%d/%Y") %></div></h2>

<p><%= raw image_tag("/code_image/#{@image.id}", :alt => "Image", :size => "160x160") %></p>
<p><p><%= @image.description %></p>


<br />

<%= link_to 'Back', :back %> | <%= link_to 'Admin Panel', posts_path %>