config/routes.rb
Motoprieks::Application.routes.draw do
  get "login" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "sign_up" => "users#new", :as => "sign_up"
  resources :users
  resources :sessions
  resources :categories
  resources :images

  match 'code_image/:id' => 'images#code_image'
  get "destroy" => "posts#destroy", :as => "destroy"
  get "admin_category" => "posts#admin_category", :as => "admin_category"
  get "create_category" => "posts#create_category", :as => "create_category"
  get "edit_category" => "posts#edit_category", :as => "edit_category"
  resources :posts do
    resources :comments
  end
  resources :mains
  get "show_category" => "mains#show_category", :as => "show_category"
  root :to => "mains#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Motoprieks</title>
  <%= stylesheet_link_tag 'style' %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <%= include_tiny_mce_if_needed %>
</head>
<body>
<div id="container">
<div id="headercont">
    <div id="headerleft">
    <%= link_to(mains_path) do %>
      <h1>Moto.<span>Prieks.</span></h1>
    <% end %>
		</div>
		<div id="headerright">
		  <ul>
		      <% if admin_user %>
            Logged in as<li><%= link_to current_user.login, current_user.website %></li>.<li>|</li>
            <li><%= link_to "Log out", log_out_path %></li><li>|</li>
            <li><%= link_to "Admin panels", posts_path %></li>
          <% elsif editor_user %>
            Logged in as<li><%= link_to current_user.login, current_user.website %></li>.<li>|</li>
            <li><%= link_to "Log out", log_out_path %></li><li>|</li>
            <li><%= link_to "Editor panels", posts_path %></li>
          <% elsif current_user %>
            Logged in as<li><%= link_to current_user.login, current_user.website %></li>.<li>|</li>
            <li><%= link_to "Log out", log_out_path %></li>
          <% else %>
            <li><%= link_to "Sign up", sign_up_path %></li><li>|</li>
            <li><%= link_to "Log in", log_in_path %></li>
          <% end %>
		  </ul>
		</div>
</div>
<% flash.each do |name, msg|%>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>
    <div id="maincont">
     <%= yield %>
		<div id="bottom"></div>
    </div>  
    
    
    <div id="footercont">
		<div id="footerleft">
			<p><a title="back to top" href="#container"><strong>^ back to top</strong></a></p>
		</div>
		<div id="footerright">
			<p><a title="derby web design" href="http://www.tristarwebdesign.co.uk">template by <strong>tristar</strong></a></p>
		</div>
	  </div>
  
</div>
</body>
</html>